version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sbtcpay-postgres
    restart: always
    environment:
      POSTGRES_DB: sbtcpay
      POSTGRES_USER: sbtcpay_user
      POSTGRES_PASSWORD: sbtcpay_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: sbtcpay-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local